name: 申请子域 | Apply new subdomain
description: 在这里申请子域 | Regist new subdomains here.
body: 
  - type: input
    attributes:
      label: 输入完整的域名 | Enter FULL subdomain.
      description: 有一些保留域名是不能选择的，比如所有单字母子域和“blog”“mc”等管理员使用中的域名。如果你选择了其他用户已经在用的域名，你可以在收到通知之后更改 | There are some reserved domains that cannot be selected, such as all single-letter parent-child domains and domains in use by administrators such as "blog" and "mc". If you choose a domain name that is already in use by another user, you can change it after receiving notification.
      placeholder: e.g. example.reitouko.cyou

  - type: dropdown
    attributes:
      label: 选择你要添加的记录 | Select the DNS record.
      description: 通常来说，Github Pages添加CNAME记录，IPv4添加A记录，IPv6添加AAAA记录 | Choose CNAME you are using GitHub Pages, A if you have an IPv4 address and AAAA if you have an IPv6 address.
      options:
        - CNAME
        - A
        - AAAA

  - type: input
    attributes:
      label: 输入你解析的内容 | Enter the record destination.
      placeholder: e.g. 1.1.1.1

  - type: checkboxes
    attributes:
      label: 大陆服务器不建议开启Cloudflare CDN
      options:
        - label: 开启Cloudflare CDN | Use Cloudflare CDN service.

  - type: checkboxes
    attributes:
      label: 冰冻广场是Reitouko的域名公布页面，让申请了reitouko.cyou子域的小伙伴们聚集起来。不过也可以选择不公开。 | The Reitouko Square is the place to organize every Reitoukers together.
      options:
        - label: 将域名公开到冰冻广场 | Publicize your subdomain to Reitouko Square.

  - type: input
    attributes:
      label: 在冰冻广场显示的标题 | Enter the title you want to show in the square.
      description: 给你的网站起个名字吧 | Name your website!
      placeholder: e.g. My Blog.

  - type: checkboxes
    attributes:
      label: 你必须同意同意下面的条款，才能使用Reitouko的服务！| You have to agree the terms below to use the service!
      options: 
        - label: 我同意不将我的网站用于宣传色情。| I agree not to use my site to promote pornography.
          - required: true
        - label: 我同意不将我的网站用于宣传针对特定人群的歧视。| I agree not to use my website to promote discrimination against specific groups of people.
          - required: true
        - label: 我同意不将我的网站用于其他违反法律的用途。| I agree not to use my website for any other purpose that violates the law.
          - required: true
        - label: 我同意Reitouko管理组可以在我违反以上条款是删除我的域名。| I agree that the Reitouko administration team can delete my domain name if I violate the above terms.
          - required: true

  - type: markdown
    attributes:
      value: "留下Email和想说的话吧！| Leave an Email and what you want to say!"
  
